### ISSUE TITLE
[Question] The license of the datasets

### ISSUE THREAD

**Issue by xiong-jie-y** [ShuhongChen/bizarre-pose-estimator#3]
Hi!

Thank you for sharing impressive model.

I'm curious about the license of the datasets you provides.
Is it AGPL3.0 too, or other license?
For example, can I add any license to the models trained with your datasets?

Thank you!

**Comment by ShuhongChen** [comment]
Hi, thanks for your kind words!

Sorry I'm not that familiar with licensing.  We picked AGPL3 because it seems to encourage open-sourcing things, so for now I'd say please try to make derivative work also open-source.

**Comment by xiong-jie-y** [comment]
I see. Thank you!
