### ISSUE TITLE
HuggingFace Demo doesn't work

### ISSUE THREAD

**Issue by julkaztwittera** [ShuhongChen/bizarre-pose-estimator#9]
No matter what image I choose, the HuggingFace demo returns the same picture from the dataset...

**Comment by ShuhongChen** [comment]
hello, sorry for the delayed response; yes, it seems like the web demo is down at the moment

unfortunately the demo wasn't contributed by the repo maintainers so it will take some work for us to fix it; in the meantime if you have any issues setting up the repo yourself please feel free to open an issue
